project:
  type: website
  pre-render: curl https://raw.githubusercontent.com/lmu-osc/branding-resources/refs/heads/main/custom.scss -o lmu-osc-custom.scss
  

website:
  title: "TUTORIAL TITLE HERE"
  page-footer: 
    center: "Copyright, 2024 Open Science Center at LMU Munich"
    border: false
  search:
    location: sidebar
  repo-url: https://github.com/lmu-osc/REPO-NAME-HERE
  repo-actions: [edit, issue]
  back-to-top-navigation: true
  page-navigation: true
  favicon: assets/LMU_OSC_favicon.jpg
  margin-header: |
    ![](/assets/LMU_OSC_logo.jpg){width="175"}
  
  
  navbar:
    right: 
      - about.qmd
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/lmu-osc/REPO-NAME-HERE
          - text: Report a Bug
            url:  https://github.com/lmu-osc/REPO-NAME-HERE/issues
      - icon: house-heart
        url: https://www.osc.uni-muenchen.de/index.html
   
        
  sidebar:
    style: "docked"
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "TOPIC 1"
        contents:
          - href: TOPIC1/page1.qmd
            text: "TOPIC1 Page1 Title"
          - href: TOPIC1/page2.qmd
            text: "TOPIC1 Page2 Title"
      - section: "TOPIC 2"
        contents:
          - href: TOPIC2/page1.qmd
            text: "TOPIC2 Page1 Title"
          - href: TOPIC2/page2.qmd
            text: "TOPIC2 Page2 Title"
          - href: TOPIC2/page3.qmd
            text: "TOPIC2 Page3 Title"



format:
  html:
    theme: 
      - cosmo
      - lmu-osc-custom.scss
    css: 
      - https://raw.githubusercontent.com/lmu-osc/branding-resources/refs/heads/main/lmu-osc-styles.css
    toc: true
    fontsize: 13pt
    code-overflow: wrap
    grid:
      sidebar-width: 300px

editor: source
