---
title: "About"
date: YYYY-MM-DD
citation:
  type: "webpage"
  title: "TITLE HERE"
  container-title: "LMU Open Science Center"
  url: https://lmu-osc.github.io/introduction-to-renv
  doi: "DOI HERE"
author:
  - name: AUTHOR 1
    affiliation: "LMU Open Science Center, OTHER AFFILIATIONS"
    orcid: 0000-0000-0000-0000
  - name: AUTHOR 2
    affiliation: "LMU Open Science Center, OTHER AFFILIATIONS"
    orcid: 0000-0000-0000-0000
# google-scholar: true
---


# Contributors

This site was authored by AUTHORS, and edits/contributions were made by EDITORS/AUTHORS.

# Licenses

The overall project is available under the **[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)** license found at [LICENSE](LICENSE.md); all code snippets are also (at your option) available under the **[CC0 1.0 Universal](https://creativecommons.org/publicdomain/zero/1.0/)** license found at [LICENSE-CODE](LICENSE-CODE.md).

Why two licenses? The CC BY-SA 4.0 license is for the content of the website, while the CC0 1.0 Universal license is for the code and configuration files. This is a common practice for websites that include code snippets and other content that may be reused in other projects, particularly because the CC BY-SA 4.0 license is not intended to be used with software.

# Notes

This tutorial was primarily written in YYYY using SOFTWARE-NAME SOFTWARE-VERSION. Major changes to the SOFTWARE-NAME can be found at the [package's website](SOFTWARE-URL) for the most up-to-date information, and to confirm that our tutorial is not out-of-date. 

