name: Link Checker

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: filiph/linkcheck@3.0.0
        with:
            arguments: https://lmu-osc.github.io/tutorial-template/