on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * 0"
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy-renv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install R with renv
        if: ${{ hashFiles('renv.lock') != ''}}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: renv

      - name: Install R Dependencies with renv
        if: ${{ hashFiles('renv.lock') != ''}}
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Install R latest
        if: ${{ hashFiles('renv.lock') == ''}}
        uses: r-lib/actions/setup-r@v2

      - name: Install R latest dependencies
        if: ${{ hashFiles('renv.lock') == ''}}
        run: |
          install.packages("renv")
          install.packages("rmarkdown")
          install.packages("yaml")
          install.packages(renv::dependencies()$Packages)
        shell: Rscript {0}

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}